### ISSUE TITLE
Remove usage of `async-timer`

### ISSUE THREAD

**Issue by IgnisDa** [geofmureithi/apalis#301]
@geofmureithi Off topic, but would it be possible to remove usage of `async-timer` [[reason](https://github.com/tokio-rs/tokio/issues/5975#issuecomment-1731921015)]?

I am getting a `BorrowedMutError` and here is the full stacktrace:
```
thread 'tokio-runtime-worker' panicked at /home/archlinux/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/scheduler/multi_thread/worker.rs:1026:49:
already borrowed: BorrowMutError
stack backtrace:
   0:     0x5bfa14e749b6 - std::backtrace_rs::backtrace::libunwind::trace::hd6ffdc229294c06f
                               at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/std/src/../../backtrace/src/backtrace/libunwind.rs:104:5
   1:     0x5bfa14e749b6 - std::backtrace_rs::backtrace::trace_unsynchronized::h991f79b6e9960513
                               at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x5bfa14e749b6 - std::sys_common::backtrace::_print_fmt::hf4ebe716f7ccda10
                               at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/std/src/sys_common/backtrace.rs:68:5
   3:     0x5bfa14e749b6 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h410d4c66be4e37f9
                               at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x5bfa14ea2760 - core::fmt::rt::Argument::fmt::he0ff0e0e188c0db5
                               at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/core/src/fmt/rt.rs:142:9
   5:     0x5bfa14ea2760 - core::fmt::write::he40921d4802ce2ac
                               at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/core/src/fmt/mod.rs:1120:17
   6:     0x5bfa14e70aff - std::io::Write::write_fmt::h5de5a4e7037c9b20
                               at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/std/src/io/mod.rs:1846:15
   7:     0x5bfa14e74794 - std::sys_common::backtrace::_print::hd8e2e3f655086663
                               at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/std/src/sys_common/backtrace.rs:47:5
   8:     0x5bfa14e74794 - std::sys_common::backtrace::print::h11c067a88e3bdb22
                               at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/std/src/sys_common/backtrace.rs:34:9
   9:     0x5bfa14e76017 - std::panicking::default_hook::{{closure}}::h8c832ecb03fde8ea
  10:     0x5bfa14e75d79 - std::panicking::default_hook::h1633e272b4150cf3
                               at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/std/src/panicking.rs:292:9
  11:     0x5bfa14e764a8 - std::panicking::rust_panic_with_hook::hb164d19c0c1e71d4
                               at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/std/src/panicking.rs:781:13
  12:     0x5bfa14e76382 - std::panicking::begin_panic_handler::{{closure}}::h0369088c533c20e9
                               at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/std/src/panicking.rs:659:13
  13:     0x5bfa14e74eb6 - std::sys_common::backtrace::__rust_end_short_backtrace::hc11d910daf35ac2e
                               at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/std/src/sys_common/backtrace.rs:171:18
  14:     0x5bfa14e760d4 - rust_begin_unwind
                               at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/std/src/panicking.rs:647:5
  15:     0x5bfa0fe34b85 - core::panicking::panic_fmt::ha6effc2775a0749c
                               at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/core/src/panicking.rs:72:14
  16:     0x5bfa0fe34a59 - core::cell::panic_already_borrowed::h0863662ba5c47ea0
                               at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/core/src/cell.rs:761:5
  17:     0x5bfa14d3b9ad - core::cell::RefCell<T>::borrow_mut::h993f65d3bfea81c6
                               at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/core/src/cell.rs:1051:25
  18:     0x5bfa14d961cf - tokio::runtime::scheduler::multi_thread::worker::<impl tokio::runtime::scheduler::multi_thread::handle::Handle>::schedule_task::{{closure}}::h5af9fb3393de8537
                               at /home/archlinux/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/scheduler/multi_thread/worker.rs:1026:41
  19:     0x5bfa14d9640e - tokio::runtime::scheduler::multi_thread::worker::with_current::{{closure}}::h2c740dbaa4a1ad5a
                               at /home/archlinux/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/scheduler/multi_thread/worker.rs:1222:35
  20:     0x5bfa14d782f8 - tokio::runtime::context::scoped::Scoped<T>::with::h86949bb37188f6f5
                               at /home/archlinux/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/context/scoped.rs:53:22
  21:     0x5bfa14d868b5 - tokio::runtime::context::with_scheduler::{{closure}}::hc948807349e8f290
                               at /home/archlinux/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/context.rs:182:30
  22:     0x5bfa14d4e1c9 - std::thread::local::LocalKey<T>::try_with::h57ecca3493a79b63
                               at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/std/src/thread/local.rs:286:16
  23:     0x5bfa14d86758 - tokio::runtime::context::with_scheduler::he4725400e385de51
                               at /home/archlinux/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/context.rs:182:9
  24:     0x5bfa14d96346 - tokio::runtime::scheduler::multi_thread::worker::with_current::h8bd04c507f47638e
                               at /home/archlinux/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/scheduler/multi_thread/worker.rs:1221:5
  25:     0x5bfa14d5cc4c - tokio::runtime::scheduler::multi_thread::worker::<impl tokio::runtime::scheduler::multi_thread::handle::Handle>::schedule_task::h7df8f72e1dfb8107
                               at /home/archlinux/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/scheduler/multi_thread/worker.rs:1021:9
  26:     0x5bfa14d19367 - tokio::runtime::scheduler::multi_thread::worker::<impl tokio::runtime::task::Schedule for alloc::sync::Arc<tokio::runtime::scheduler::multi_thread::handle::Handle>>::schedule::h98710c205f66aa0a
                               at /home/archlinux/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/scheduler/multi_thread/worker.rs:1011:9
  27:     0x5bfa14662890 - tokio::runtime::task::raw::schedule::hf31141ac4e1f1bb0
                               at /home/archlinux/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/task/raw.rs:278:5
  28:     0x5bfa14d87a88 - tokio::runtime::task::raw::RawTask::schedule::h255e10d4068073da
                               at /home/archlinux/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/task/raw.rs:206:18
  29:     0x5bfa14d871e7 - tokio::runtime::task::harness::<impl tokio::runtime::task::raw::RawTask>::wake_by_val::hf287b4691e45de94
                               at /home/archlinux/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/task/harness.rs:78:17
  30:     0x5bfa14d885b9 - tokio::runtime::task::waker::wake_by_val::h0bf0f6919609e0ef
                               at /home/archlinux/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/task/waker.rs:85:5
  31:     0x5bfa14e16e09 - core::task::wake::Waker::wake::hed1c5d1bab9f369d
                               at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/core/src/task/wake.rs:285:18
  32:     0x5bfa14e14ffe - <futures_util::future::future::shared::Notifier as futures_task::arc_wake::ArcWake>::wake_by_ref::hb5f45e294b2ef7ea
                               at /home/archlinux/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.30/src/future/future/shared.rs:394:21
  33:     0x5bfa11fab364 - futures_task::arc_wake::ArcWake::wake::h85cf494fff720530
                               at /home/archlinux/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-task-0.3.30/src/arc_wake.rs:32:9
  34:     0x5bfa0ff3d12f - futures_task::waker::wake_arc_raw::h268cf878850f1e71
                               at /home/archlinux/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-task-0.3.30/src/waker.rs:47:5
  35:     0x5bfa14c79259 - core::task::wake::Waker::wake::hbda0a0eea27cfa0b
                               at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/core/src/task/wake.rs:285:18
  36:     0x5bfa14c7a303 - async_timer::state::AtomicWaker::wake::hba31d2a88a1569b4
                               at /home/archlinux/.cargo/registry/src/index.crates.io-6f17d22bba15001f/async-timer-1.0.0-beta.13/src/state.rs:175:17
  37:     0x5bfa14c7a48a - async_timer::state::TimerState::wake::h3237ed3214385ffc
                               at /home/archlinux/.cargo/registry/src/index.crates.io-6f17d22bba15001f/async-timer-1.0.0-beta.13/src/state.rs:248:13
  38:     0x5bfa14c7a4f0 - async_timer::timer::posix::ffi::timer_handler::hf4b3b720c6284460
                               at /home/archlinux/.cargo/registry/src/index.crates.io-6f17d22bba15001f/async-timer-1.0.0-beta.13/src/timer/posix.rs:25:9
  39:     0x7e5f30046770 - <unknown>
  40:     0x5bfa14d99831 - core::ptr::drop_in_place<core::cell::RefMut<core::option::Option<alloc::boxed::Box<tokio::runtime::scheduler::multi_thread::worker::Core>>>>::hfcaedd39d8406186
                               at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/core/src/ptr/mod.rs:507
  41:     0x5bfa14d93d23 - tokio::runtime::scheduler::multi_thread::worker::Context::run_task::{{closure}}::h804358ee8ed36016
                               at /home/archlinux/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/scheduler/multi_thread/worker.rs:592:18
  42:     0x5bfa14d93a64 - tokio::runtime::coop::with_budget::h9202cb8576d7b066
                               at /home/archlinux/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/coop.rs:107:5
  43:     0x5bfa14d93a64 - tokio::runtime::coop::budget::h50fb991606c87a01
                               at /home/archlinux/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/coop.rs:73:5
  44:     0x5bfa14d93a64 - tokio::runtime::scheduler::multi_thread::worker::Context::run_task::h5abaf72c76f03082
                               at /home/archlinux/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/scheduler/multi_thread/worker.rs:575:9
  45:     0x5bfa14d93101 - tokio::runtime::scheduler::multi_thread::worker::Context::run::h592b453d1ae7e628
                               at /home/archlinux/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/scheduler/multi_thread/worker.rs:526:24
  46:     0x5bfa14d92d59 - tokio::runtime::scheduler::multi_thread::worker::run::{{closure}}::{{closure}}::h2bba30f02f737469
                               at /home/archlinux/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/scheduler/multi_thread/worker.rs:491:21
  47:     0x5bfa14d77f80 - tokio::runtime::context::scoped::Scoped<T>::set::h2b68fd3b8403f48c
                               at /home/archlinux/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/context/scoped.rs:40:9
  48:     0x5bfa14d865eb - tokio::runtime::context::set_scheduler::{{closure}}::hce56cd710386b2a1
                               at /home/archlinux/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/context.rs:176:26
  49:     0x5bfa14d4ee60 - std::thread::local::LocalKey<T>::try_with::hd28b7532b0093cce
                               at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/std/src/thread/local.rs:286:16
  50:     0x5bfa14d4d3bb - std::thread::local::LocalKey<T>::with::h39377088af52eda9
                               at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/std/src/thread/local.rs:262:9
  51:     0x5bfa14d86524 - tokio::runtime::context::set_scheduler::h3211ea45b3f3bb56
                               at /home/archlinux/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/context.rs:176:9
  52:     0x5bfa14d92c61 - tokio::runtime::scheduler::multi_thread::worker::run::{{closure}}::h4ab5ceecce9c6ebd
                               at /home/archlinux/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/scheduler/multi_thread/worker.rs:486:9
  53:     0x5bfa14d9fd88 - tokio::runtime::context::runtime::enter_runtime::hb0e755042dfde361
                               at /home/archlinux/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/context/runtime.rs:65:16
  54:     0x5bfa14d929fc - tokio::runtime::scheduler::multi_thread::worker::run::h57db502b30203a07
                               at /home/archlinux/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/scheduler/multi_thread/worker.rs:478:5
  55:     0x5bfa14d9286b - tokio::runtime::scheduler::multi_thread::worker::Launch::launch::{{closure}}::h80b49406e46ca010
                               at /home/archlinux/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/scheduler/multi_thread/worker.rs:447:45
  56:     0x5bfa14d5fc9e - <tokio::runtime::blocking::task::BlockingTask<T> as core::future::future::Future>::poll::h82284a2ba441bf4e
                               at /home/archlinux/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/blocking/task.rs:42:21
  57:     0x5bfa14d4872c - tokio::runtime::task::core::Core<T,S>::poll::{{closure}}::h49b8d959926c55e8
                               at /home/archlinux/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/task/core.rs:328:17
  58:     0x5bfa14d485df - tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut::h06da256dd80dc07c
                               at /home/archlinux/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/loom/std/unsafe_cell.rs:16:9
  59:     0x5bfa14d485df - tokio::runtime::task::core::Core<T,S>::poll::he9bcbc43cdc90579
                               at /home/archlinux/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/task/core.rs:317:13
  60:     0x5bfa14dac2b5 - tokio::runtime::task::harness::poll_future::{{closure}}::h37a6cfa670022d2c
                               at /home/archlinux/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/task/harness.rs:485:19
  61:     0x5bfa14d23cc4 - <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h89025b7785c331bc
                               at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/core/src/panic/unwind_safe.rs:272:9
  62:     0x5bfa14d38666 - std::panicking::try::do_call::hd20cc771786bcb28
                               at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/std/src/panicking.rs:554:40
  63:     0x5bfa14d39c6b - __rust_try
  64:     0x5bfa14d36c38 - std::panicking::try::h5c30541b1e8cf24b
                               at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/std/src/panicking.rs:518:19
  65:     0x5bfa14d531db - std::panic::catch_unwind::h895f71638576beb3
                               at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/std/src/panic.rs:142:14
  66:     0x5bfa14dabd6f - tokio::runtime::task::harness::poll_future::hc18bab4b04ef9888
                               at /home/archlinux/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/task/harness.rs:473:18
  67:     0x5bfa14da8583 - tokio::runtime::task::harness::Harness<T,S>::poll_inner::h4c7a06f3c345f7ba
                               at /home/archlinux/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/task/harness.rs:208:27
  68:     0x5bfa14da8317 - tokio::runtime::task::harness::Harness<T,S>::poll::h7b2ad4885e5a3bf5
                               at /home/archlinux/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/task/harness.rs:153:15
  69:     0x5bfa14d87d8d - tokio::runtime::task::raw::poll::h97370f97c7ef1de7
                               at /home/archlinux/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/task/raw.rs:271:5
  70:     0x5bfa14d87a57 - tokio::runtime::task::raw::RawTask::poll::h42e114e1dacc1cc3
                               at /home/archlinux/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/task/raw.rs:201:18
  71:     0x5bfa14d519e7 - tokio::runtime::task::UnownedTask<S>::run::hcfdee9108a22eab5
                               at /home/archlinux/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/task/mod.rs:464:9
  72:     0x5bfa14d3f267 - tokio::runtime::blocking::pool::Task::run::hed57a7cdf9ae1061
                               at /home/archlinux/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/blocking/pool.rs:159:9
  73:     0x5bfa14d42e49 - tokio::runtime::blocking::pool::Inner::run::h2529ab29fc09f654
                               at /home/archlinux/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/blocking/pool.rs:513:17
  74:     0x5bfa14d42b64 - tokio::runtime::blocking::pool::Spawner::spawn_thread::{{closure}}::h91036ec4371434d0
                               at /home/archlinux/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/blocking/pool.rs:471:13
  75:     0x5bfa14d97116 - std::sys_common::backtrace::__rust_begin_short_backtrace::hccc7dc9efd7fe6f7
                               at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/std/src/sys_common/backtrace.rs:155:18
  76:     0x5bfa14d3b3e2 - std::thread::Builder::spawn_unchecked_::{{closure}}::{{closure}}::h070538d26d8db0f0
                               at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/std/src/thread/mod.rs:529:17
  77:     0x5bfa14d239d2 - <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h2f5eb3652863d697
                               at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/core/src/panic/unwind_safe.rs:272:9
  78:     0x5bfa14d37fc3 - std::panicking::try::do_call::h3487af2ba6a98491
                               at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/std/src/panicking.rs:554:40
  79:     0x5bfa14d39c6b - __rust_try
  80:     0x5bfa14d36d01 - std::panicking::try::h5c7fb6aee4dd2988
                               at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/std/src/panicking.rs:518:19
  81:     0x5bfa14d3b1ef - std::panic::catch_unwind::h851e786a2bb19095
                               at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/std/src/panic.rs:142:14
  82:     0x5bfa14d3b1ef - std::thread::Builder::spawn_unchecked_::{{closure}}::h594064164f77fc00
                               at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/std/src/thread/mod.rs:528:30
  83:     0x5bfa14d9777f - core::ops::function::FnOnce::call_once{{vtable.shim}}::h255f348165691479
                               at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/core/src/ops/function.rs:250:5
  84:     0x5bfa14e79cb5 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h6b630278c760b971
                               at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/alloc/src/boxed.rs:2015:9
  85:     0x5bfa14e79cb5 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h70462b441b6c0e1f
                               at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/alloc/src/boxed.rs:2015:9
  86:     0x5bfa14e79cb5 - std::sys::pal::unix::thread::Thread::new::thread_start::h3631815ad38387d6
                               at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/std/src/sys/pal/unix/thread.rs:108:17
  87:     0x7e5f3009555a - <unknown>
  88:     0x7e5f30112894 - clone
  89:                0x0 - <unknown>
```

It has calls to `async-timer` and `apalis` is the only one which uses this crate.
![image](https://github.com/geofmureithi/apalis/assets/60938164/c35aacfd-2b2f-40ca-9d90-4ce050e5d18b)

**Comment by IgnisDa** [comment]
I see this has already been addressed here: https://github.com/geofmureithi/apalis/pull/291#issuecomment-2047036064.

@mikonieminen Sorry for tagging you. Were you able to solve this problem?

**Comment by IgnisDa** [comment]
Can confirm that downgrading to `v0.4.9` fixes the issue.

**Comment by mikonieminen** [comment]
@IgnisDa I have my separate branch that replaces use of `async-timer` with `sleep` from `tokio` or `async-std`, but the approach is not desirable. I also have some preliminary work on better solution, but wiring the runtime through all layers is a bit painful and I haven't had time to finish it.

You can still find the branch from: https://github.com/mikonieminen/apalis/tree/fix/async-timer-causing-panics

**Comment by IgnisDa** [comment]
@geofmureithi Any updates on this?

**Comment by geofmureithi** [comment]
@IgnisDa  Will be releasing version 0.6 alpha over the weekend.

**Comment by IgnisDa** [comment]
@geofmureithi Could you cut a new release?
