### ISSUE TITLE
Postgres example throws error

### ISSUE THREAD

**Issue by dfberry** [geofmureithi/apalis#476]
The postgres example throws an error. 

My steps: 

1. clone repo
2. open repo in dev container with rust: `cargo 1.81.0 (2dbb1af80 2024-08-20)`
3. add my own empty postgres url
4. cargo build - no errors
5. cargo build - errors

```console
cargo run
   Compiling proc-macro2 v1.0.92
   Compiling libc v0.2.167
   Compiling serde v1.0.215
   Compiling typenum v1.17.0
   Compiling generic-array v0.14.7
   Compiling lock_api v0.4.12
   Compiling parking_lot_core v0.9.10
   Compiling crossbeam-utils v0.8.20
   Compiling num-traits v0.2.19
   Compiling ahash v0.8.11
   Compiling thiserror v1.0.69
   Compiling paste v1.0.15
   Compiling rustix v0.38.41
   Compiling apalis-sql v0.6.0
   Compiling quote v1.0.37
   Compiling syn v2.0.90
   Compiling concurrent-queue v2.5.0
   Compiling crossbeam-queue v0.3.11
   Compiling getrandom v0.2.15
   Compiling socket2 v0.5.8
   Compiling mio v1.0.3
   Compiling rand_core v0.6.4
   Compiling cpufeatures v0.2.16
   Compiling signal-hook-registry v1.4.2
   Compiling event-listener v5.3.1
   Compiling atoi v2.0.0
   Compiling chrono v0.4.38
   Compiling tempfile v3.14.0
   Compiling synstructure v0.13.1
   Compiling serde_derive v1.0.215
   Compiling zerocopy-derive v0.7.35
   Compiling zerofrom-derive v0.1.5
   Compiling yoke-derive v0.7.5
   Compiling zerovec-derive v0.10.3
   Compiling displaydoc v0.2.5
   Compiling icu_provider_macros v1.5.0
   Compiling tracing-attributes v0.1.28
   Compiling futures-macro v0.3.31
   Compiling zerocopy v0.7.35
   Compiling tokio-macros v2.4.0
   Compiling thiserror-impl v1.0.69
   Compiling zerofrom v0.1.5
   Compiling block-buffer v0.10.4
   Compiling yoke v0.7.5
   Compiling ppv-lite86 v0.2.20
   Compiling crypto-common v0.1.6
   Compiling zerovec v0.10.4
   Compiling digest v0.10.7
   Compiling futures-util v0.3.31
   Compiling rand_chacha v0.3.1
   Compiling rand v0.8.5
   Compiling hashbrown v0.14.5
   Compiling tracing v0.1.41
   Compiling thiserror-impl v2.0.5
   Compiling tinystr v0.7.6
   Compiling icu_collections v1.5.0
   Compiling hashlink v0.9.1
   Compiling ulid v1.1.3
   Compiling icu_locid v1.5.0
   Compiling sha2 v0.10.8
   Compiling hmac v0.12.1
   Compiling hkdf v0.12.4
   Compiling icu_provider v1.5.0
   Compiling md-5 v0.10.6
   Compiling thiserror v2.0.5
   Compiling icu_locid_transform v1.5.0
   Compiling futures-executor v0.3.31
   Compiling async-stream-impl v0.3.6
   Compiling tracing-futures v0.2.5
   Compiling futures v0.3.31
   Compiling icu_properties v1.5.1
   Compiling async-stream v0.3.6
   Compiling smallvec v1.13.2
   Compiling serde_json v1.0.133
   Compiling either v1.13.0
   Compiling email_address v0.2.9
   Compiling tracing-subscriber v0.3.19
   Compiling parking_lot v0.12.3
   Compiling tokio v1.42.0
   Compiling futures-intrusive v0.5.0
   Compiling icu_normalizer v1.5.0
   Compiling idna_adapter v1.2.0
   Compiling idna v1.0.3
   Compiling url v2.5.4
   Compiling sqlx-core v0.8.2
   Compiling tower v0.5.1
   Compiling tokio-util v0.7.13
   Compiling tower v0.4.13
   Compiling apalis-core v0.6.0
   Compiling apalis-core v0.6.0 (/workspaces/packages/apalis-core)
   Compiling sqlx-postgres v0.8.2
   Compiling apalis v0.6.0
   Compiling apalis v0.6.0 (/workspaces)
   Compiling email-service v0.1.0 (/workspaces/examples/email-service)
   Compiling sqlx-macros-core v0.8.2
   Compiling sqlx-macros v0.8.2
   Compiling sqlx v0.8.2
   Compiling postgres-example v0.1.0 (/workspaces/examples/postgres)
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 27.51s
     Running `/workspaces/target/debug/postgres-example`
thread 'main' panicked at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/sqlx-core-0.8.2/src/pool/inner.rs:57:24:
either the `runtime-async-std` or `runtime-tokio` feature must be enabled
stack backtrace:
   0: rust_begin_unwind
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/panicking.rs:665:5
   1: core::panicking::panic_fmt
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/panicking.rs:74:14
   2: sqlx_core::rt::missing_rt
             at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/sqlx-core-0.8.2/src/rt/mod.rs:143:5
   3: sqlx_core::sync::AsyncSemaphore::new
             at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/sqlx-core-0.8.2/src/sync.rs:34:13
   4: sqlx_core::pool::inner::PoolInner<DB>::new_arc
             at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/sqlx-core-0.8.2/src/pool/inner.rs:57:24
   5: sqlx_core::pool::options::PoolOptions<DB>::connect_with::{{closure}}
             at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/sqlx-core-0.8.2/src/pool/options.rs:544:21
   6: sqlx_core::pool::options::PoolOptions<DB>::connect::{{closure}}
             at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/sqlx-core-0.8.2/src/pool/options.rs:529:41
   7: sqlx_core::pool::Pool<DB>::connect::{{closure}}
             at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/sqlx-core-0.8.2/src/pool/mod.rs:283:47
   8: postgres_example::main::{{closure}}
             at ./src/main.rs:30:47
   9: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/future/future.rs:123:9
  10: tokio::runtime::park::CachedParkThread::block_on::{{closure}}
             at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.42.0/src/runtime/park.rs:281:63
  11: tokio::runtime::coop::with_budget
             at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.42.0/src/runtime/coop.rs:107:5
  12: tokio::runtime::coop::budget
             at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.42.0/src/runtime/coop.rs:73:5
  13: tokio::runtime::park::CachedParkThread::block_on
             at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.42.0/src/runtime/park.rs:281:31
  14: tokio::runtime::context::blocking::BlockingRegionGuard::block_on
             at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.42.0/src/runtime/context/blocking.rs:66:9
  15: tokio::runtime::scheduler::multi_thread::MultiThread::block_on::{{closure}}
             at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.42.0/src/runtime/scheduler/multi_thread/mod.rs:87:13
  16: tokio::runtime::context::runtime::enter_runtime
             at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.42.0/src/runtime/context/runtime.rs:65:16
  17: tokio::runtime::scheduler::multi_thread::MultiThread::block_on
             at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.42.0/src/runtime/scheduler/multi_thread/mod.rs:86:9
  18: tokio::runtime::runtime::Runtime::block_on_inner
             at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.42.0/src/runtime/runtime.rs:370:45
  19: tokio::runtime::runtime::Runtime::block_on
             at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.42.0/src/runtime/runtime.rs:340:13
  20: postgres_example::main
             at ./src/main.rs:61:5
  21: core::ops::function::FnOnce::call_once
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

Cargo.toml
```toml
[package]
name = "postgres-example"
version = "0.1.0"
authors = ["Njuguna Mureithi <mureithinjuguna@gmail.com>"]
edition = "2018"
license = "MIT OR Apache-2.0"

[dependencies]
anyhow = "1"
apalis = { version = "0.6.0", features = ["retry"] }
apalis-sql = { version = "0.6.0", features = ["postgres", "migrate"] }
serde = "1"
tracing-subscriber = "0.3.11"
chrono = { version = "0.4", default-features = false, features = ["clock"] }
tokio = { version = "1", features = ["full"] }
email-service = { path = "../email-service" }
tower = { version = "0.4", features = ["buffer"] }

[dependencies.tracing]
default-features = false
version = "0.1"
```

main.rs
```rust
use anyhow::Result;
use apalis::layers::retry::RetryPolicy;

use apalis::prelude::*;
use apalis_sql::postgres::{PgListen, PgPool, PostgresStorage};
use email_service::{send_email, Email};
use tracing::{debug, info};

async fn produce_jobs(storage: &mut PostgresStorage<Email>) -> Result<()> {
    for index in 0..10 {
        storage
            .push(Email {
                to: format!("test{}@example.com", index),
                text: "Test background job from apalis".to_string(),
                subject: "Background email job".to_string(),
            })
            .await?;
    }
    // The sql way
    tracing::info!("You can also add jobs via sql query, run this: \n Select apalis.push_job('apalis::Email', json_build_object('subject', 'Test apalis', 'to', 'test1@example.com', 'text', 'Lorem Ipsum'));");
    Ok(())
}

#[tokio::main]
async fn main() -> Result<()> {
    std::env::set_var("RUST_LOG", "debug,sqlx::query=error");
    tracing_subscriber::fmt::init();
    let database_url = "postgresql://..."; // removed

    let pool = PgPool::connect(&database_url).await?;
    PostgresStorage::setup(&pool)
        .await
        .expect("unable to run migrations for postgres");

    let mut pg = PostgresStorage::new(pool.clone());
    produce_jobs(&mut pg).await?;

    let mut listener = PgListen::new(pool).await?;

    listener.subscribe_with(&mut pg);

    tokio::spawn(async move {
        listener.listen().await.unwrap();
    });

    Monitor::new()
        .register({
            WorkerBuilder::new("tasty-orange")
                .enable_tracing()
                .retry(RetryPolicy::retries(5))
                .backend(pg)
                .build_fn(send_email)
        })
        .on_event(|e| debug!("{e}"))
        .run_with_signal(async {
            tokio::signal::ctrl_c().await?;
            info!("Shutting down the system");
            Ok(())
        })
        .await?;
    Ok(())
}
```

**Comment by geofmureithi** [comment]
Consider specifying the features for `sqlx`:
```
[dependencies.sqlx]
version = "0.8"
default-features = false
features = ["postgres", "runtime-tokio"]
```

**Comment by geofmureithi** [comment]
I will update the examples
